# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: 
      - master
    tags:        
      - v* 
  pull_request:
    branches: 
      - master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    strategy:
      matrix:
        runner: [windows-latest, ubuntu-latest, macos-latest]
    runs-on:
      - ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Test
        run: mvn clean test

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Package & Deploy (Release)
        if: startsWith(github.ref, 'refs/tags/v')
        run: mvn deploy -DaltDeploymentRepository=internal.repo::default::https://maven.totalcross.com/artifactory/repo1-release -DskipTests=true -Dinternal.repo.username=${{ secrets.TC_MVN_REPO_USR }} -Dinternal.repo.password=${{ secrets.TC_MVN_REPO_PASS }} -s settings.xml

      - name: Package & Deploy (Nightly)
        if: contains(github.ref, 'master')
        run: mvn versions:set -DnewVersion=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)-$(TZ=GMT date +"%Y%m%d%H%M") && mvn deploy -DaltDeploymentRepository=internal.repo::default::https://maven.totalcross.com/artifactory/nightly -DskipTests=true -Dinternal.repo.username=${{ secrets.TC_MVN_REPO_USR }} -Dinternal.repo.password=${{ secrets.TC_MVN_REPO_PASS }} -s settings.xml
