# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: 
      - master
      - feature/actions-ci
  pull_request:
    branches: 
      - master 
      - feature/actions-ci

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    strategy:
      matrix:
        runner: [windows-latest, ubuntu-latest, macos-latest]
    steps: 
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Test
        runs-on:
          - ${{ matrix.runner }}
        run: mvn clean test

      - name: Package & Deploy
        runs-on: ubuntu-latest
        run:
          - >-
            mvn deploy
            -DskipTests=true
            -Dinternal.repo.username=${{ secrets.TC_MVN_REPO_USR }}
            -Dinternal.repo.password=${{ secrets.TC_MVN_REPO_PASS }}
            -s settings.xml
  